Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -26,5 +26,14 @@ jobs:
         run: docker compose -f docker-compose.yml up -d
       - name: Build Docker image
         run: docker ps    
-      - name: Testing frontend endpoint
-        run: curl http://localhost:5173  
+      - name: Wait for frontend
+        run: |
+          for i in {1..15}; do
+          if curl -s http://localhost:5173 > /dev/null; then
+          echo "Frontend is up!"
+          exit 0
+          fi
+          echo "Waiting for frontend..."
+          sleep 3
+          done
+          echo "Frontend failed to start" && exit 1
